### ISSUE TITLE
[iOS] Audio session activation failed when app is in background

### ISSUE THREAD

**Issue by Frayo44** [ryanheise/audio_session#102]
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(560557684, Session activation failed, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
#2      AVAudioSession.setActive (package:audio_session/src/darwin.dart:150:8)
<asynchronous suspension>
#3      AudioSession.setActive (package:audio_session/src/core.dart:237:14)
<asynchronous suspension>
#4      AudioSessionLocal.setActive (package:bus_station_alarm_clock/utils/alarm/audio_session_local.dart:25:5)
<asynchronous suspension>
#5      AlarmLocal.playAlarm (package:bus_station_alarm_clock/utils/alarm/alarm_local.dart:28:5)
<asynchronous suspension>

**Comment by ChrisElliotUK** [comment]
Have you added the audio background mode to your iOS permissions?

**Comment by sbauly** [comment]
Hi @Frayo44, did you manage to find a fix for this?

**Comment by vikasdhaka16** [comment]
Hey did u find the solution
