### ISSUE TITLE
failed for task ':audio_session:compileReleaseJavaWithJavac' (target SDK 33)

### ISSUE THREAD

**Issue by Mykerinos** [ryanheise/audio_session#126]
Hi,
i have an error while compilation : 

> warning: [options] source value 8 is obsolete and will be removed in a future release
> [        ] warning: [options] target value 8 is obsolete and will be removed in a future release
> [        ] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
> [        ] error: warnings found and -Werror specified
> [        ] FAILURE: Build failed with an exception.
> [        ] * What went wrong:
> [        ] Execution failed for task ':audio_session:compileReleaseJavaWithJavac'.
> [        ] > Compilation failed; see the compiler error output for details.
> [        ] * Try:
> [        ] > Run with --debug option to get more log output.
> [        ] > Run with --scan to get full insights.
> [        ] * Exception is:
> [        ] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':audio_session:compileReleaseJavaWithJavac'.
> [        ]      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
> [        ]      at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
> [        ]      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:140)
> [        ]      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:128)
> [        ]      at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
> [        ]      at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
> [        ]      at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
> [        ]      at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
> [        ]      at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
> [   +3 ms]      at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
> ...

I use : 
pubspec.yaml : 

> just_audio: ^0.9.36
> audio_session 0.1.18

app/build.gradle : 

> compileSdkVersion 33
> minSdkVersion 23
> targetSdkVersion 33

build.gradle : 

>     dependencies {
>         classpath 'com.android.tools.build:gradle:7.4.2'
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>         classpath 'com.google.gms:google-services:4.3.14'
>     }

I read #108 , but my case concerns targetSDK 33

please let me know if you need more information...

Thanks for your answer...

**Comment by Mykerinos** [comment]
My solution : 
- I compile with JDK11
- I use Kotlin v1.8.22
