### ISSUE TITLE
Exception in AndroidAudioManager.getMicrophones()

### ISSUE THREAD

**Issue by toebgen** [ryanheise/audio_session#64]
First of all, thanks a lot for this great package, I am really a big fan!

While playing around with the `AndroidAudioManager` I noticed that the `getMicrophones()` function throws an exception.
I am well aware that it is marked as "UNTESTED". Anyways, it probably makes sense to note some test results here.

API level on my device: 30.
Flutter:

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
```

The error message I receive is:
```
E/flutter ( 5854): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: type '_InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>' in type cast
E/flutter ( 5854): #0      _CastListBase.[] (dart:_internal/cast.dart:99:46)
E/flutter ( 5854): #1      ListMixin.elementAt (dart:collection/list.dart:78:33)
E/flutter ( 5854): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:40)
E/flutter ( 5854): #3      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
E/flutter ( 5854): #4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
E/flutter ( 5854): #5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
E/flutter ( 5854): #6      new List.of (dart:core-patch/array_patch.dart:51:28)
E/flutter ( 5854): #7      ListIterable.toList (dart:_internal/iterable.dart:213:44)
E/flutter ( 5854): #8      AndroidAudioManager.getMicrophones
```

Minimal example:
```dart
import 'package:audio_session/audio_session.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) => const MaterialApp(
        home: MyHomePage(),
      );
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
    AudioSession.instance.then((audioSession) async {
      await audioSession.configure(const AudioSessionConfiguration.music());
    });
  }

  Future<void> _getMicrophones() async {
    final androidAudioManager = AndroidAudioManager();
    final microphones = await androidAudioManager.getMicrophones();
    if (kDebugMode) {
      print('${microphones.length} microphones found');
    }
  }

  @override
  Widget build(BuildContext context) => Scaffold(
        body: const Center(
          child: Text('Get microphones'),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: _getMicrophones,
          child: const Icon(Icons.mic_external_on_rounded),
        ),
      );
}
```

**Comment by ryanheise** [comment]
FYI I plan to release this fix within the next day, so it will be good if you are able to test before then if you want to ensure the next release contains a working fix for you.

**Comment by ryanheise** [comment]
This is now published, so I'll close the issue. I can reopen if you later if you find it not working.
